import os, re, json, shutil, tempfile, subprocess, secrets
from pathlib import Path
from fastapi import FastAPI, Header, HTTPException
from fastapi.responses import FileResponse
from starlette.background import BackgroundTask
from pydantic import BaseModel

app = FastAPI(title="Governor Flutter Runtime", docs_url=None, redoc_url=None)
ROOT = Path(os.environ.get("RUNTIME_WORK_DIR", "/tmp/governor-runtime"))
PREVIEWS = ROOT / "previews"
ROOT.mkdir(parents=True, exist_ok=True)
PREVIEWS.mkdir(parents=True, exist_ok=True)
TOKEN = os.environ.get("RUNTIME_SHARED_SECRET", "")
PUBLIC_URL = os.environ.get("PUBLIC_RUNTIME_URL", "").rstrip("/")
MAX_FILES = 300
MAX_BYTES = 2_000_000
PATH_RE = re.compile(r"^[A-Za-z0-9_.@/-]+$")

class BuildRequest(BaseModel):
    files: dict[str, str]

def authorize(value: str | None):
    if not TOKEN or len(TOKEN) < 32:
        raise HTTPException(503, "Runtime shared secret is not configured.")
    if not value or not secrets.compare_digest(value, TOKEN):
        raise HTTPException(401, "Unauthorized runtime request.")

def clean_files(files: dict[str, str]):
    if not isinstance(files, dict) or len(files) > MAX_FILES:
        raise HTTPException(400, "Invalid workspace file map.")
    total = 0
    cleaned = {}
    for name, content in files.items():
        if not isinstance(name, str) or not isinstance(content, str):
            continue
        path = Path(name)
        if not name or len(name) > 180 or path.is_absolute() or any(part in ("", ".", "..") for part in name.split("/")) or "\\" in name or not PATH_RE.fullmatch(name):
            raise HTTPException(400, "Unsafe project path rejected.")
        if name.startswith(".git/") or name.startswith("build/") or name.startswith(".dart_tool/"):
            continue
        if name == "pubspec_overrides.yaml" or name.startswith(("android/", "ios/", "linux/", "macos/", "windows/", "web/")):
            raise HTTPException(400, "Platform build files are generated by the runtime and cannot be overridden.")
        if len(content.encode("utf-8")) > 200_000:
            raise HTTPException(413, "A file exceeds 200 KB.")
        total += len(content.encode("utf-8"))
        if total > MAX_BYTES:
            raise HTTPException(413, "Project exceeds 2 MB.")
        cleaned[name] = content
    if "lib/main.dart" not in cleaned:
        raise HTTPException(400, "Project must include lib/main.dart.")
    manifest = cleaned.get("pubspec.yaml", "")
    if re.search(r"(?m)^\s*(git|path)\s*:", manifest) or re.search(r"(?m)^\s*(dependency_overrides|hooks|scripts)\s*:", manifest):
        raise HTTPException(400, "Git/path dependencies and custom build hooks are blocked by the hosted build service.")
    return cleaned

def prepare(files: dict[str, str], dest: Path):
    for name, content in files.items():
        target = dest / name
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
    pubspec = dest / "pubspec.yaml"
    if not pubspec.exists():
        pubspec.write_text("name: governor_generated_app\ndescription: Generated by Governor Studio\npublish_to: none\nversion: 1.0.0+1\nenvironment:\n  sdk: '>=3.4.0 <4.0.0'\ndependencies:\n  flutter:\n    sdk: flutter\ndev_dependencies:\n  flutter_test:\n    sdk: flutter\nflutter:\n  uses-material-design: true\n", encoding="utf-8")

def run(command, cwd: Path, timeout=480):
    try:
        result = subprocess.run(command, cwd=str(cwd), text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, timeout=timeout, check=False, env={**os.environ, "CI":"true"})
    except subprocess.TimeoutExpired as error:
        raise HTTPException(504, "Flutter build timed out. Reduce dependencies or project size.")
    if result.returncode:
        log = (result.stdout or "")[-12000:]
        raise HTTPException(422, "Flutter build failed:\n" + log)
    return result.stdout[-5000:]

@app.get("/health")
def health():
    return {"ok": True, "flutter": True}

@app.post("/build/web")
def build_web(body: BuildRequest, x_runtime_token: str | None = Header(default=None)):
    authorize(x_runtime_token)
    files = clean_files(body.files)
    build_id = secrets.token_urlsafe(18)
    with tempfile.TemporaryDirectory(prefix="gov-web-") as tmp:
        work = Path(tmp) / "project"
        work.mkdir()
        prepare(files, work)
        run(["flutter", "create", "--platforms=web", "--project-name", "governor_generated_app", "."], work, 180)
        run(["flutter", "pub", "get"], work, 180)
        run(["flutter", "build", "web", "--release", "--base-href", f"/preview/{build_id}/"], work, 480)
        target = PREVIEWS / build_id
        shutil.copytree(work / "build" / "web", target)
    if not PUBLIC_URL:
        shutil.rmtree(target, ignore_errors=True)
        raise HTTPException(503, "Set PUBLIC_RUNTIME_URL to the public HTTPS URL of this runtime service.")
    return {"previewUrl": f"{PUBLIC_URL}/preview/{build_id}/index.html", "buildId": build_id, "engine": "Flutter Web release build"}

@app.post("/build/apk")
def build_apk(body: BuildRequest, x_runtime_token: str | None = Header(default=None)):
    authorize(x_runtime_token)
    files = clean_files(body.files)
    tmp = tempfile.mkdtemp(prefix="gov-apk-")
    work = Path(tmp) / "project"
    work.mkdir()
    prepare(files, work)
    try:
        run(["flutter", "create", "--platforms=android", "--project-name", "governor_generated_app", "."], work, 180)
        run(["flutter", "pub", "get"], work, 180)
        run(["flutter", "analyze"], work, 180)
        run(["flutter", "build", "apk", "--release"], work, 480)
        apk = work / "build" / "app" / "outputs" / "flutter-apk" / "app-release.apk"
        if not apk.exists():
            raise HTTPException(500, "Flutter build finished without an APK output.")
        return FileResponse(apk, media_type="application/vnd.android.package-archive", filename="governor-project-release.apk", background=BackgroundTask(shutil.rmtree, tmp, ignore_errors=True))
    finally:
        # Keep temporary directory while FileResponse streams; a system temp cleanup handles it later.
        pass

@app.get("/preview/{build_id}/{asset_path:path}")
def preview(build_id: str, asset_path: str):
    if not re.fullmatch(r"[A-Za-z0-9_-]{10,80}", build_id):
        raise HTTPException(404, "Preview not found.")
    root = (PREVIEWS / build_id).resolve()
    path = (root / (asset_path or "index.html")).resolve()
    if root not in path.parents and path != root:
        raise HTTPException(400, "Invalid asset path.")
    if not path.is_file():
        raise HTTPException(404, "Preview asset not found.")
    media = "application/wasm" if path.suffix == ".wasm" else None
    return FileResponse(path, media_type=media)
